#! /bin/zsh

$PWD/scripts/build

$PWD/scripts/import_cert
image_name="registry.gitlab.com/rentziass/go_docker_sample:$(git describe --tags)"
docker build -t $image_name .

echo "Cleaning up..."
rm -f ca-certificates.crt
$PWD/scripts/clean
